WITH BASE_VENTAS AS
(
SELECT
PED.DOCENTRY_PED AS DOCENTRY_PED,
PED.DOCNUM_PED AS DOCNUM_PED,
PED.LINENUM_PED AS LINENUM_PED,
PED.DOCSTATUS AS DOCSTATUS_PED,
PED.CREATEDATE AS CREATEDATE_PED,
PED.CANCELED_PED AS CANCELED_PED,
PED.PRICE * PED.QUANTITY AS LINETOTAL_PED,
FACT_AGG.DOCENTRY_FACT AS DOCENTRY_FACT,
FACT_AGG.FECHAEMISION_FACT AS FECHAEMISION_FACT,
PICK_AGG.PICKUPDATE_PICK AS PICKUPDATE_PICK,
CLI.CLIENT_NAME AS CLIENT_NAME_CLI
FROM
STD_MEX_BI_PEDIDOS ped
LEFT JOIN 
(
SELECT * FROM 
STD_MEX_BI_CLIENTES
WHERE 
UPPER(ADDRESS_TYPE) LIKE '%FISCAL%'
OR CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
OR (CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)>1) 
    AND  
    CLIENT_CODE||'-'||ADDRESS_TYPE IN (
        SELECT CLIENT_CODE||'-'||ADDRESS_TYPE 
        FROM(
        SELECT CLIENT_CODE, MAX(ADDRESS_TYPE) AS ADDRESS_TYPE 
        FROM STD_MEX_BI_CLIENTES 
        WHERE ADDRESS_TYPE<>'Ship To' 
        GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
    )
    )
) 
cli ON ped.CARDCODE = cli.CLIENT_CODE
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        MAX(fact.DOCENTRY) AS DOCENTRY_FACT,
        MAX(fact.U_FECHAEMISION) AS FECHAEMISION_FACT
    FROM 
        STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
    LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) FACT_AGG ON FACT_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND FACT_AGG.LINENUM_PED = ped.LINENUM_PED
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        MAX(pick.UPDATEDATE) AS PICKUPDATE_PICK
    FROM STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_PICK pick ON pick.ORDERENTRY = pl.DOCENTRY_PED
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) PICK_AGG ON PICK_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND PICK_AGG.LINENUM_PED = ped.LINENUM_PED
),
VENTAS_FECHADEF AS
(
SELECT
    BASE_VENTAS.*,
    (CASE
        WHEN BASE_VENTAS.FECHAEMISION_FACT IS NOT NULL 
        THEN BASE_VENTAS.FECHAEMISION_FACT
        WHEN BASE_VENTAS.DOCENTRY_FACT IS NULL 
        THEN    
            (
                CASE 
                    WHEN BASE_VENTAS.CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND BASE_VENTAS.PICKUPDATE_PICK IS NULL
                    THEN BASE_VENTAS.CREATEDATE_PED
                    WHEN BASE_VENTAS.CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND BASE_VENTAS.PICKUPDATE_PICK IS NOT NULL
                    THEN SYSDATE
                    WHEN BASE_VENTAS.DOCSTATUS_PED = 'C'
                    THEN BASE_VENTAS.CREATEDATE_PED
                    WHEN BASE_VENTAS.DOCSTATUS_PED = 'O'
                    THEN SYSDATE
                    ELSE NULL
                END
            )
        WHEN BASE_VENTAS.DOCENTRY_FACT IS NOT NULL AND BASE_VENTAS.FECHAEMISION_FACT IS NULL
        THEN BASE_VENTAS.CREATEDATE_PED
    END) AS FECHADEF
FROM BASE_VENTAS
),
VENTAS_DEDUP AS
(
SELECT VD.*
FROM
(
    SELECT
        VF2.*,
        ROW_NUMBER() OVER (PARTITION BY VF2.DOCENTRY_PED, VF2.LINENUM_PED ORDER BY VF2.DOCENTRY_PED) AS RN_DEDUP
    FROM VENTAS_FECHADEF VF2
) VD
WHERE VD.RN_DEDUP = 1
),
TOTAL_POR_DOC AS
(
SELECT
    FECHADEF,
    DOCENTRY_PED,
    DOCNUM_PED,
    COUNT(*) AS LINEAS_EN_EL_DOC,
    SUM(LINETOTAL_PED) AS TOTAL_PEDIDO_DOC
FROM VENTAS_DEDUP
GROUP BY FECHADEF, DOCENTRY_PED, DOCNUM_PED
)
SELECT * FROM TOTAL_POR_DOC
WHERE DOCNUM_PED = '21750';

SELECT
    TRUNC(FECHADEF, 'MM') AS MES_PEDIDO,
    COUNT(DISTINCT DOCENTRY_PED) AS PEDIDOS_DISTINTOS,
    COUNT(*) AS FILAS_TOTAL_POR_DOC,
    SUM(TOTAL_PEDIDO_DOC) AS TOTAL_PEDIDOS_FECHA
FROM
(
    SELECT FECHADEF, DOCENTRY_PED, DOCNUM_PED, SUM(LINETOTAL_PED) AS TOTAL_PEDIDO_DOC
    FROM
    (
    WITH BASE_VENTAS AS
    (
    SELECT
    PED.DOCENTRY_PED AS DOCENTRY_PED,
    PED.DOCNUM_PED AS DOCNUM_PED,
    PED.LINENUM_PED AS LINENUM_PED,
    PED.DOCSTATUS AS DOCSTATUS_PED,
    PED.CREATEDATE AS CREATEDATE_PED,
    PED.CANCELED_PED AS CANCELED_PED,
    PED.PRICE * PED.QUANTITY AS LINETOTAL_PED,
    FACT_AGG.DOCENTRY_FACT AS DOCENTRY_FACT,
    FACT_AGG.FECHAEMISION_FACT AS FECHAEMISION_FACT,
    PICK_AGG.PICKUPDATE_PICK AS PICKUPDATE_PICK,
    CLI.CLIENT_NAME AS CLIENT_NAME_CLI
    FROM
    STD_MEX_BI_PEDIDOS ped
    LEFT JOIN 
    (
    SELECT * FROM 
    STD_MEX_BI_CLIENTES
    WHERE 
    UPPER(ADDRESS_TYPE) LIKE '%FISCAL%'
    OR CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
    OR (CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)>1) 
        AND  
        CLIENT_CODE||'-'||ADDRESS_TYPE IN (
            SELECT CLIENT_CODE||'-'||ADDRESS_TYPE 
            FROM(
            SELECT CLIENT_CODE, MAX(ADDRESS_TYPE) AS ADDRESS_TYPE 
            FROM STD_MEX_BI_CLIENTES 
            WHERE ADDRESS_TYPE<>'Ship To' 
            GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
        )
        )
    ) 
    cli ON ped.CARDCODE = cli.CLIENT_CODE
    LEFT JOIN
    (
        SELECT
            pl.DOCENTRY_PED,
            pl.LINENUM_PED,
            MAX(fact.DOCENTRY) AS DOCENTRY_FACT,
            MAX(fact.U_FECHAEMISION) AS FECHAEMISION_FACT
        FROM 
            STD_MEX_BI_PEDIDOS pl
        LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
        LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
        GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
    ) FACT_AGG ON FACT_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND FACT_AGG.LINENUM_PED = ped.LINENUM_PED
    LEFT JOIN
    (
        SELECT
            pl.DOCENTRY_PED,
            pl.LINENUM_PED,
            MAX(pick.UPDATEDATE) AS PICKUPDATE_PICK
        FROM STD_MEX_BI_PEDIDOS pl
        LEFT JOIN STD_MEX_BI_PICK pick ON pick.ORDERENTRY = pl.DOCENTRY_PED
        GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
    ) PICK_AGG ON PICK_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND PICK_AGG.LINENUM_PED = ped.LINENUM_PED
    ),
    VENTAS_FECHADEF AS
    (
    SELECT
        BASE_VENTAS.*,
        (CASE
            WHEN BASE_VENTAS.FECHAEMISION_FACT IS NOT NULL 
            THEN BASE_VENTAS.FECHAEMISION_FACT
            WHEN BASE_VENTAS.DOCENTRY_FACT IS NULL 
            THEN    
                (
                    CASE 
                        WHEN BASE_VENTAS.CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND BASE_VENTAS.PICKUPDATE_PICK IS NULL
                        THEN BASE_VENTAS.CREATEDATE_PED
                        WHEN BASE_VENTAS.CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND BASE_VENTAS.PICKUPDATE_PICK IS NOT NULL
                        THEN SYSDATE
                        WHEN BASE_VENTAS.DOCSTATUS_PED = 'C'
                        THEN BASE_VENTAS.CREATEDATE_PED
                        WHEN BASE_VENTAS.DOCSTATUS_PED = 'O'
                        THEN SYSDATE
                        ELSE NULL
                    END
                )
            WHEN BASE_VENTAS.DOCENTRY_FACT IS NOT NULL AND BASE_VENTAS.FECHAEMISION_FACT IS NULL
            THEN BASE_VENTAS.CREATEDATE_PED
        END) AS FECHADEF
    FROM BASE_VENTAS
    ),
    VENTAS_DEDUP AS
    (
    SELECT VD.*
    FROM
    (
        SELECT
            VF2.*,
            ROW_NUMBER() OVER (PARTITION BY VF2.DOCENTRY_PED, VF2.LINENUM_PED ORDER BY VF2.DOCENTRY_PED) AS RN_DEDUP
        FROM VENTAS_FECHADEF VF2
    ) VD
    WHERE VD.RN_DEDUP = 1
    )
    SELECT * FROM VENTAS_DEDUP
    )
    GROUP BY FECHADEF, DOCENTRY_PED, DOCNUM_PED
)
GROUP BY TRUNC(FECHADEF, 'MM')
ORDER BY 1;
