CREATE TABLE STD_MEX_BI_VENTAS_MODELO_FINAL AS
WITH BASE_VENTAS AS
(
SELECT
PED.DOCENTRY_PED AS DOCENTRY_PED,
PED.DOCNUM_PED AS DOCNUM_PED,
PED.LINENUM_PED AS LINENUM_PED,
PED.DOCDATE AS DOC_PED,
PED.DOCDUEDATE AS DOCDUE_PED,
PED.TAXDATE AS TAX_PED,
PED.DOCSTATUS AS DOCSTATUS_PED,
PED.CREATEDATE AS CREATEDATE_PED,
PED.CANCELED_PED AS CANCELED_PED,
PED.CARDCODE AS CARDCODE_PED,
PED.CARDNAME AS CARDNAME_PED,
PED.COMMENTS AS COMMENTS_PED,
PED.ITEMCODE AS ITEMCODE_PED,
PED.ITEMNAME AS ITEMNAME_PED,
PED.ITEMCODE_AGROUPED AS ITEMCODE_AGROUPED_PED,
PED.ITEMNAME_AGROUPED AS ITEMNAME_AGROUPED_PED,
PED.ITEMCODE_GROUP AS ITEMCODE_GROUP_PED,
PED.ITEMNAME_GROUP AS ITEMNAME_GROUP_PED,
PED.BRAND AS BRAND_PED,
PED.LINE AS LINE_PED,
PED.RANGE AS RANGE_PED,
PED.REGULATORY_STATUS AS REGULATORY_STATUS_PED,
PED.THERAPEUTIC_AREA AS THERAPEUTIC_AREA_PED,
PED.TYPE AS TYPE_PED,
PED.SUBTYPE AS SUBTYPE_PED,
PED.QUANTITY AS QUANTITY_PED,
PED.OPENQTY AS OPENQTY_PED,
PED.PRICE AS PRICE_PED,
PED.PRICE * PED.QUANTITY AS LINETOTAL_PED,
PED.ACCTCODE AS ACCTCODE_PED,
PED.ACCTNAME AS ACCTNAME_PED,
PED.OCRCODE AS OCRCODE_PED,
PED.OCRNAME AS OCRNAME_PED,
FACT_AGG.CANTIDAD_FACTURAS AS CANTIDAD_FACTURAS,
FACT_AGG.CANTIDAD_FACTURAS_CANCELADAS AS CANTIDAD_FACTURAS_CANCELADAS,
FACT_AGG.DOCENTRY_FACT AS DOCENTRY_FACT,
FACT_AGG.DOCNUM_FACT AS DOCNUM_FACT,
FACT_AGG.FECHAEMISION_FACT AS FECHAEMISION_FACT,
FACT_AGG.PRECIO_ULTIMA_FACTURA AS PRECIO_ULTIMA_FACTURA,
FACT_AGG.PEYMETHOD_ULTIMA_FACTURA AS PEYMETHOD_ULTIMA_FACTURA,
FACT_AGG.RATE_ULTIMA_FACTURA AS RATE_ULTIMA_FACTURA,
FACT_AGG.IVAVALUE_ULTIMA_FACTURA AS IVAVALUE_ULTIMA_FACTURA,
FACT_AGG.IVAGROUP_ULTIMA_FACTURA AS IVAGROUP_ULTIMA_FACTURA,
FACT_AGG.FECHA_PRIMERA_FACTURA AS FECHA_PRIMERA_FACTURA,
FACT_AGG.FECHA_ULTIMA_ACTUALIZACION_FACT AS FECHA_ULTIMA_ACTUALIZACION_FACT,
FACT_AGG.FACTURAS_ASOCIADAS AS FACTURAS_ASOCIADAS,
NVL(FACT_AGG.TOT_PARTIDA,0) AS LINETOTAL_FACT,
NVL(FACT_AGG.TOTAL_DESCUENTO_FACT,0) AS TOTAL_DESCUENTO_FACT,
NVL(FACT_AGG.TOTAL_IVA_FACT,0) AS TOTAL_IVA_FACT,
ENTR_AGG.CANTIDAD_ENTREGAS AS CANTIDAD_ENTREGAS,
ENTR_AGG.CANTIDAD_ENTREGAS_CANCELADAS AS CANTIDAD_ENTREGAS_CANCELADAS,
NVL(ENTR_AGG.CANTIDAD_ENTREGADA_TOTAL,0) AS CANTIDAD_ENTREGADA_TOTAL,
ENTR_AGG.FECHA_PRIMERA_ENTREGA AS FECHA_PRIMERA_ENTREGA,
ENTR_AGG.FECHA_ULTIMA_ACTUALIZACION_ENTR AS FECHA_ULTIMA_ACTUALIZACION_ENTR,
ENTR_AGG.ENTREGAS_ASOCIADAS AS ENTREGAS_ASOCIADAS,
PAGOS_AGG.CANTIDAD_PAGOS AS CANTIDAD_PAGOS,
PAGOS_AGG.CANTIDAD_PAGOS_CANCELADOS AS CANTIDAD_PAGOS_CANCELADOS,
PAGOS_AGG.TOTAL_PAGADO AS TOTAL_PAGADO,
PAGOS_AGG.TOTAL_TRANSFERIDO AS TOTAL_TRANSFERIDO,
PAGOS_AGG.TOTAL_IVA_PAGADO AS TOTAL_IVA_PAGADO,
PAGOS_AGG.FECHA_ULTIMO_PAGO AS FECHA_ULTIMO_PAGO,
PAGOS_AGG.FECHA_ULTIMA_TRANSFERENCIA AS FECHA_ULTIMA_TRANSFERENCIA,
PAGOS_AGG.CUENTAS_TRANSFERENCIA_ASOCIADAS AS CUENTAS_TRANSFERENCIA_ASOCIADAS,
PAGOS_AGG.REFERENCIAS_PAGO_ASOCIADAS AS REFERENCIAS_PAGO_ASOCIADAS,
PAGOS_AGG.PAGOS_ASOCIADOS AS PAGOS_ASOCIADOS,
PICK_AGG.PICKUPDATE_PICK AS PICKUPDATE_PICK,
CLI.CLIENT_CODE AS CLIENT_CODE_CLI,
CLI.CLIENT_NAME AS CLIENT_NAME_CLI,
CLI.VAT_TAX_ID AS VAT_TAX_ID_CLI,
CLI.CLIENT_SUBTYPE AS CLIENT_SUBTYPE_CLI,
CLI.CLIENT_SUBTYPE2 AS CLIENT_SUBTYPE2_CLI,
CLI.STATUS AS STATUS_CLI,
CLI.CURRENCY AS CURRENCY_CLI,
CLI.GROUPED_CLIENT_CODE AS GROUPED_CLIENT_CODE_CLI,
CLI.GROUPED_CLIENT_NAME AS GROUPED_CLIENT_NAME_CLI,
CLI.DATE_CLIENT AS DATE_CLIENT_CLI,
CLI.CLIENT_ASSIGNED_SALES_FORCE AS CLIENT_ASSIGNED_SALES_FORCE_CLI,
CLI.NETWORK_TERRITORY AS NETWORK_TERRITORY_CLI,
CLI.FINANCIAL_RISK AS FINANCIAL_RISK_CLI,
CLI.ELECTRONIC_BILLING AS ELECTRONIC_BILLING_CLI,
CLI.PAYMENT_CONDITIONS AS PAYMENT_CONDITIONS_CLI,
CLI.ADDRESS AS ADDRESS_CLI,
CLI.ADDRESS_TYPE AS ADDRESS_TYPE_CLI,
CLI.DATE_ADDRESS AS DATE_ADDRESS_CLI,
CLI.CONTINENT AS CONTINENT_CLI,
CLI.COUNTRY AS COUNTRY_CLI,
CLI.STATE AS STATE_CLI,
CLI.CITY AS CITY_CLI,
CLI.PHONE AS PHONE_CLI,
CLI.EMAIL AS EMAIL_CLI,
CLI.VALIDATE_STATUS AS VALIDATE_STATUS_CLI,
CLI.ACCOUNT_NUM AS ACCOUNT_NUM_CLI,
CLI.ACCOUNT_NAME AS ACCOUNT_NAME_CLI,
CLI.VATGROUP  AS VATGROUP_CLI
FROM
STD_MEX_BI_PEDIDOS ped
LEFT JOIN 
(
SELECT * FROM 
STD_MEX_BI_CLIENTES
WHERE 
UPPER(ADDRESS_TYPE) LIKE '%FISCAL%'
OR CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
OR (CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)>1) 
    AND  
    CLIENT_CODE||'-'||ADDRESS_TYPE IN (
        SELECT CLIENT_CODE||'-'||ADDRESS_TYPE 
        FROM(
        SELECT CLIENT_CODE, MAX(ADDRESS_TYPE) AS ADDRESS_TYPE 
        FROM STD_MEX_BI_CLIENTES 
        WHERE ADDRESS_TYPE<>'Ship To' 
        GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
    )
    )
) 
cli ON ped.CARDCODE = cli.CLIENT_CODE
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        COUNT(fact.DOCENTRY) AS CANTIDAD_FACTURAS,
        SUM(CASE WHEN fact.CANCELED = 'Y' THEN 1 ELSE 0 END) AS CANTIDAD_FACTURAS_CANCELADAS,
        SUM(fact.LINETOTAL) AS TOT_PARTIDA,
        SUM(fact.DESCUENTO) AS TOTAL_DESCUENTO_FACT,
        SUM(fact.VATSUM) AS TOTAL_IVA_FACT,
        MAX(fact.DOCENTRY) AS DOCENTRY_FACT,
        MAX(fact.DOCNUM) AS DOCNUM_FACT,
        MAX(fact.U_FECHAEMISION) AS FECHAEMISION_FACT,
        MAX(fact.PRECIO) KEEP (DENSE_RANK LAST ORDER BY fact.DOCENTRY) AS PRECIO_ULTIMA_FACTURA,
        MAX(fact.PEYMETHOD) KEEP (DENSE_RANK LAST ORDER BY fact.DOCENTRY) AS PEYMETHOD_ULTIMA_FACTURA,
        MAX(fact.RATE) KEEP (DENSE_RANK LAST ORDER BY fact.DOCENTRY) AS RATE_ULTIMA_FACTURA,
        MAX(fact.IVAVALUE) KEEP (DENSE_RANK LAST ORDER BY fact.DOCENTRY) AS IVAVALUE_ULTIMA_FACTURA,
        MAX(fact.IVAGROUP) KEEP (DENSE_RANK LAST ORDER BY fact.DOCENTRY) AS IVAGROUP_ULTIMA_FACTURA,
        MIN(fact.FECHACRE) AS FECHA_PRIMERA_FACTURA,
        MAX(fact.FECHAACT) AS FECHA_ULTIMA_ACTUALIZACION_FACT,
        LISTAGG(fact.DOCNUM,', ') WITHIN GROUP (ORDER BY fact.DOCNUM) AS FACTURAS_ASOCIADAS
    FROM 
        STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
    LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) FACT_AGG ON FACT_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND FACT_AGG.LINENUM_PED = ped.LINENUM_PED
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        COUNT(entr.DOCENTRY) AS CANTIDAD_ENTREGAS,
        SUM(CASE WHEN entr.CANCELED = 'Y' THEN 1 ELSE 0 END) AS CANTIDAD_ENTREGAS_CANCELADAS,
        SUM(entr.CANTIDADENTREGADA) AS CANTIDAD_ENTREGADA_TOTAL,
        MIN(entr.FECHACRE) AS FECHA_PRIMERA_ENTREGA,
        MAX(entr.FECHAACT) AS FECHA_ULTIMA_ACTUALIZACION_ENTR,
        LISTAGG(entr.DOCNUM,', ') WITHIN GROUP (ORDER BY entr.DOCNUM) AS ENTREGAS_ASOCIADAS
    FROM
        STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) ENTR_AGG ON ENTR_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND ENTR_AGG.LINENUM_PED = ped.LINENUM_PED
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        COUNT(pays.DOCNUM_PAGOS) AS CANTIDAD_PAGOS,
        SUM(CASE WHEN pays.CANCELED = 'Y' THEN 1 ELSE 0 END) AS CANTIDAD_PAGOS_CANCELADOS,
        SUM(pays.SUMAPPLIED) AS TOTAL_PAGADO,
        SUM(pays.TRSFRSUM) AS TOTAL_TRANSFERIDO,
        SUM(pays.VATAPPLIED) AS TOTAL_IVA_PAGADO,
        MAX(pays.FECHACRE) AS FECHA_ULTIMO_PAGO,
        MAX(pays.TRSFRDATE) AS FECHA_ULTIMA_TRANSFERENCIA,
        LISTAGG(pays.TRSFRACCT,', ') WITHIN GROUP (ORDER BY pays.TRSFRACCT) AS CUENTAS_TRANSFERENCIA_ASOCIADAS,
        LISTAGG(pays.TRSFRREF,', ') WITHIN GROUP (ORDER BY pays.TRSFRREF) AS REFERENCIAS_PAGO_ASOCIADAS,
        LISTAGG(pays.DOCNUM_PAGOS,', ') WITHIN GROUP (ORDER BY pays.DOCNUM_PAGOS) AS PAGOS_ASOCIADOS
    FROM
        STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
    LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
    LEFT JOIN STD_MEX_BI_PAGOS pays ON pays.INVTYPE = '13' AND pays.DOCENTRY_REL = fact.DOCENTRY
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) PAGOS_AGG ON PAGOS_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND PAGOS_AGG.LINENUM_PED = ped.LINENUM_PED
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        MAX(pick.UPDATEDATE) AS PICKUPDATE_PICK
    FROM STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_PICK pick ON pick.ORDERENTRY = pl.DOCENTRY_PED
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) PICK_AGG ON PICK_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND PICK_AGG.LINENUM_PED = ped.LINENUM_PED
),
VENTAS_FECHADEF AS
(
SELECT
    BASE_VENTAS.*,
    (CASE
        WHEN BASE_VENTAS.FECHAEMISION_FACT IS NOT NULL 
        THEN BASE_VENTAS.FECHAEMISION_FACT
        WHEN BASE_VENTAS.DOCENTRY_FACT IS NULL 
        THEN    
            (
                CASE 
                    WHEN BASE_VENTAS.GROUPED_CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND BASE_VENTAS.PICKUPDATE_PICK IS NULL
                    THEN BASE_VENTAS.CREATEDATE_PED
                    WHEN BASE_VENTAS.GROUPED_CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND BASE_VENTAS.PICKUPDATE_PICK IS NOT NULL
                    THEN SYSDATE
                    WHEN BASE_VENTAS.DOCSTATUS_PED = 'C'
                    THEN BASE_VENTAS.CREATEDATE_PED
                    WHEN BASE_VENTAS.DOCSTATUS_PED = 'O'
                    THEN SYSDATE
                    ELSE NULL
                END
            )
        WHEN BASE_VENTAS.DOCENTRY_FACT IS NOT NULL AND BASE_VENTAS.FECHAEMISION_FACT IS NULL
        THEN BASE_VENTAS.CREATEDATE_PED
    END) AS FECHADEF,
    (CASE WHEN BASE_VENTAS.DOCENTRY_FACT IS NOT NULL THEN 'SI' ELSE 'NO' END) AS TIENE_FACTURA,
    (CASE 
        WHEN BASE_VENTAS.DOCENTRY_FACT IS NULL AND BASE_VENTAS.DOCSTATUS_PED = 'O'
        THEN 'Pendiente de facturar'
        WHEN BASE_VENTAS.DOCSTATUS_PED = 'C' AND BASE_VENTAS.DOCENTRY_FACT IS NULL
        THEN 'No facturado'
        WHEN BASE_VENTAS.DOCENTRY_FACT IS NOT NULL AND BASE_VENTAS.LINETOTAL_PED > NVL(BASE_VENTAS.LINETOTAL_FACT,0)
        THEN 'No facturado'
        ELSE 'Facturado'
    END) AS FACTURADO,
    BASE_VENTAS.LINETOTAL_PED - NVL(BASE_VENTAS.LINETOTAL_FACT,0) AS IMPORTE_FALTANTE_FACTURA
FROM BASE_VENTAS
)
SELECT
    VF.*,
    SUM(VF.LINETOTAL_PED) OVER (PARTITION BY VF.FECHADEF, VF.DOCENTRY_PED, VF.DOCNUM_PED) AS TOTAL_PEDIDO_DOC,
    SUM(VF.LINETOTAL_PED) OVER (PARTITION BY TRUNC(VF.FECHADEF, 'MM')) AS TOTAL_PEDIDOS_FECHA
FROM VENTAS_FECHADEF VF
;
